### ISSUE TITLE
[TODO]: Botão de adicionar vídeo no editor de posts

### ISSUE THREAD

**Issue by ViniFranco** [ancaphub/ancaphub#31]
#### Lista de tarefas:
- [x] Criar uma caixa para digitar o link
- [x] Mostrar pré-visualização do vídeo após a inserção do link
- [x] Botão que confirma a adição depois da inserção do link

Essa issue será editada com o andamento do desenvolvimento e fechada após seu término.
