### ISSUE TITLE
[TODO]: Widgets

### ISSUE THREAD

**Issue by ViniFranco** [ancaphub/ancaphub#35]
#### Lista de tarefas:

- [x] Widget de itens recentes na biblioteca
- [x] Widget de assuntos do momento
- [x] Widget de uso geral para mostrar perfis, por exemplo
